import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    marginHorizontal: 20,
    borderRadius: 16,
    overflow: "hidden",
    height: 200,
  },
  pressableContainer: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    position: "relative",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  backgroundImage: {
    position: "absolute",
    width: "100%",
    height: "100%",
    zIndex: 0,
  },
  swipeOverlay: {
    position: "absolute",
    width: "100%",
    height: "100%",
    zIndex: 1,
  },
  pressed: {
    opacity: 0.8,
  },
  gradient: {
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    zIndex: 2,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "60%",
  },
  contentContainer: {
    height: "100%",
    justifyContent: "flex-end",
    paddingBottom: 8,
  },
  content: {
    padding: 16,
  },
  header: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 60,
    zIndex: 3,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    flex: 1,
    marginRight: 8,
    textShadowColor: "rgba(0, 0, 0, 0,9)",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  description: {
    color: "rgba(255, 255, 255, 0.85)",
    fontSize: 13,
    marginBottom: 6,
  },
  bottomSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 8,
  },
  locationContainer: {
    flex: 1,
    marginRight: 16,
  },
  location: {
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: 12,
    lineHeight: 16,
  },
  dateContainer: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    minWidth: 50,
  },
  day: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    lineHeight: 20,
  },
  month: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 10,
    fontWeight: "600",
    lineHeight: 12,
  },
  likeButton: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 3,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  heartFull: {
    fontSize: 20,
    color: "#FF4444",
  },
  heartEmpty: {
    fontSize: 20,
    color: "#FFFFFF",
  },
  participationBadge: {
    position: "absolute",
    top: 40,
    left: 12,
    backgroundColor: "rgba(76, 175, 80, 0.9)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: "flex-start",
    marginTop: 4,
    marginBottom: 8,
  },
  participationText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
});

